spring:
  profiles:
    active: dev

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - nickname
              - email
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 10MB  # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: 10MB  # multipart/form-data 요청의 최대 허용 크기. 기본 10MB
      enabled: true


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}  # 버킷의 리전
    s3:
      bucket: ${AWS_BUCKET}     # 버킷 이름
    stack:
      auto: false



jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpirationTime: 900000          # 15분 (밀리초 기준)
  refreshTokenExpirationTime: 1209600000     # 14일