#db:
#  server: ${DB_SERVER}
#  port: ${DB_PORT}
#  username: ${DB_USER}
#  password: ${DB_PASS}
#
#redis:
#  host: ${REDIS_HOST}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT}/nyangDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASS}