version: '3'
services:
  nyang1:  # 서비스 이름은 컨테이너간 통신하기 위한 이름
    build: .
    env_file:
      - .env
    image: nyang
    restart: always
    container_name: nyang1
    ports:
      - "8080:8080"
    environment:
      PROJECT_NAME: 백앤드 서버1
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - nyang_server
networks:
  nyang_server:
    external: true
